### ISSUE TITLE
About Usetap

### ISSUE THREAD

**Issue by ciajoe** [AMartinNo1/Usetap#10]
The "About Usetap" window is some kinde of irritating because when you (for example) clicking the "hosted on Github" link the small "about" window is all the time in the foreground... No chance to get it in to the background.

**Comment by AMartinNo1** [comment]
The reason beyond the "on top" behaviour is that it should always be more in front than the Usetap WorkZone form.

However, this is an unwanted side-effected. Further I noticed "About Usetap" can be opened unlimited times. I will take care of both till release of v1.1.0.

**Comment by AMartinNo1** [comment]
The about form will be displayed in the taskbar now and is no longer on top of all forms. Further it cannot be opened multiple times anylonger.
