### ISSUE TITLE
Unhandled Exeption when removing the last language

### ISSUE THREAD

**Issue by ciajoe** [AMartinNo1/Usetap#11]
I added a language a and a language b. Then pressed i the button remove (without marking something). The language b was removed. When i pressed remove again to remove also a, a error occurred.

************** Ausnahmetext **************
System.ArgumentOutOfRangeException: InvalidArgument=Value mit dem Wert 1 ist für index ungültig.
Parametername: index
   bei System.Windows.Forms.DataGridViewColumnCollection.RemoveAt(Int32 index)
   bei Usetap.View.WorkZone.buttonRemoveLanguage_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by AMartinNo1** [comment]
The temporary attributes in the own DataGridView class will be resetted on column deletion now.
