### ISSUE TITLE
Save when something was deleted

### ISSUE THREAD

**Issue by ciajoe** [AMartinNo1/Usetap#3]
When a language was deleted (or a translation row) and you Save it via Project->Save the file is not correct updated. You have to "Save as" new file.

Additionally if you save something the text in the status bar says furthermore that there are unsaved changes (only when deleted things are present, if you save when added something new all is ok with the text).

**Comment by AMartinNo1** [comment]
Fixed in local version. How does the save method work: When the current project has not been saved yet or the file has been deleted the saveAs-method will be triggered. Otherwise the file will be overriden.
